[package]
name = "embed_lisp"
version = "0.1.0"
edition = "2024"

[dependencies]
colorize = { git = "https://github.com/pike-rippo/colorize.git" }
parking_lot = "0.12.5"
thiserror = "2.0.17"
tokio = { version = "1.48.0", features = ["full"], optional = true }

[features]
default = []
async = ["tokio"]
